FROM alpine:latest

RUN apk update && apk add --no-cache nginx && rm -rf /var/cache/apk

COPY ./conf.d /etc/nginx/conf.d
COPY ./nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /run/php && \
    mkdir -p /var/www/html && \
    chown -R nginx:nginx /run/php  /var/www/html && \
    chmod -R 775 /run/php && \
    chmod -R 755 /var/www/html

WORKDIR /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

