FROM alpine:latest

LABEL maintainer="Dikamen <dikamenchanel@systems>" \
    architecture="amd64/x86_64" \
    mariadb-version="11.04.8" \
    alpine-version="3.21.1" \
    build="14-Dec-2024" \
    org.opencontainers.image.title="alpine-mariadb" \
    org.opencontainers.image.description="MariaDB Container image running on Alpine Linux" \
    org.opencontainers.image.authors="Dikamen <dikamenchanel@systems>" \
    org.opencontainers.image.vendor="Dikamen" \
    org.opencontainers.image.version="0.1v" \
    org.opencontainers.image.source="https://github.com/dikamenchanel/web-lemp-alpine.git"
    # org.opencontainers.image.base.name="docker.io/yobasystems/alpine:3.20.2" \
    # org.opencontainers.image.revision=$VCS_REF \
    # org.opencontainers.image.created=$BUILD_DATE

RUN apk add --no-cache mariadb mariadb-client  pwgen && \
    rm -f /var/cache/apk/*

ADD run.sh /scripts/run.sh

COPY my.cnf /etc/my.cnf

RUN mkdir /docker-entrypoint-initdb.d && \
    mkdir /scripts/pre-exec.d && \
    mkdir /scripts/pre-init.d && \
    chmod -R 755 /scripts


RUN mariadb-install-db --user=mysql --datadir=/var/lib/mysql

EXPOSE 3306

ENTRYPOINT ["/scripts/run.sh"]